-- DROP USER FIEVETL;

CREATE TABLE "FIEVETL"."ABSENCES_DATA"
(	"IDETUDIANT" NUMBER(*,0),
     "NOM" VARCHAR2(100),
     "PRENOM" VARCHAR2(100),
     "IDCOURS" VARCHAR2(100),
     "IDMODULE" VARCHAR2(100),
     "NOMMODULE" VARCHAR2(100),
     "IDSEMESTRE" VARCHAR2(100),
     "PROMOTION" VARCHAR2(100),
     "NUMSEMESTRE" VARCHAR2(100),
     "JOURABSENCE" VARCHAR2(100),
     "ESTABS" VARCHAR2(100),
     "ESTJUST" VARCHAR2(100),
     "MATIN" VARCHAR2(100),
     "MOTIFABSENCE" VARCHAR2(100)
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."ANNEE"
(	"ANNEE" NUMBER(*,0),
     PRIMARY KEY ("ANNEE")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
             PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
             BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965743" ON "FIEVETL"."ANNEE" ("ANNEE")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."ASSOVILLECODEPOSTAL"
(	"NOMVILLE" VARCHAR2(100),
     "CODEPOSTALE" NUMBER(*,0),
     PRIMARY KEY ("NOMVILLE", "CODEPOSTALE")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION DEFERRED
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965806" ON "FIEVETL"."ASSOVILLECODEPOSTAL" ("NOMVILLE", "CODEPOSTALE")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."BAC"
(	"APPELATIONBAC" VARCHAR2(100),
     PRIMARY KEY ("APPELATIONBAC")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
             PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
             BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965725" ON "FIEVETL"."BAC" ("APPELATIONBAC")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."BACNOTE"
(	"IDETUDIANT" VARCHAR2(100),
     "MATIERE" VARCHAR2(100),
     "NOTE" NUMBER(15,10),
     PRIMARY KEY ("IDETUDIANT", "MATIERE")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION DEFERRED
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965815" ON "FIEVETL"."BACNOTE" ("IDETUDIANT", "MATIERE")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."BUREAU"
(	"NUMBUREAU" VARCHAR2(100),
     "TELEPHONEBUREAU" VARCHAR2(100),
     PRIMARY KEY ("NUMBUREAU")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
             PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
             BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965737" ON "FIEVETL"."BUREAU" ("NUMBUREAU")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."COURS"
(	"IDCOURS" VARCHAR2(100),
     "IDSEMESTRE" VARCHAR2(100) NOT NULL ENABLE,
     "IDMODULE" VARCHAR2(100) NOT NULL ENABLE,
     PRIMARY KEY ("IDCOURS")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION DEFERRED
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965767" ON "FIEVETL"."COURS" ("IDCOURS")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."COURSEVALUATION"
(	"IDCOURS" VARCHAR2(100),
     "IDEVALUATION" VARCHAR2(100),
     PRIMARY KEY ("IDCOURS", "IDEVALUATION")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION DEFERRED
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965800" ON "FIEVETL"."COURSEVALUATION" ("IDCOURS", "IDEVALUATION")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."COURS_ENSEIGNANTS_DATA"
(	"IDCOURS" NUMBER(*,0),
     "IDSEMESTRE" NUMBER(*,0),
     "PROMOTION" VARCHAR2(100),
     "NUMSEMESTRE" NUMBER(*,0),
     "IDMODULE" NUMBER(*,0),
     "NOMMODULE" VARCHAR2(100),
     "CODEMODULE" VARCHAR2(100),
     "HEURES_CM" FLOAT(63),
     "HEURES_TD" FLOAT(63),
     "HEURES_TP" FLOAT(63),
     "COEFFICIENTMODULE" FLOAT(63),
     "IDUE" NUMBER(*,0),
     "NOMUE" VARCHAR2(100),
     "CODEUE" VARCHAR2(100),
     "COEFFICIENTFUE" FLOAT(63),
     "ECTS" FLOAT(63),
     "IDENSEIGNANTRESPONSABLE" NUMBER(*,0),
     "NOMENSEIGNANTRESPONSABLE" VARCHAR2(100),
     "PRENOMENSEIGNANTRESPONSABLE" VARCHAR2(100),
     "IDINTERVENANT" NUMBER(*,0),
     "NOMINTERVENANT" VARCHAR2(100),
     "PRENOMINTERVENANT" VARCHAR2(100)
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."DATES"
(	"DATES" VARCHAR2(100),
     PRIMARY KEY ("DATES")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
             PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
             BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965726" ON "FIEVETL"."DATES" ("DATES")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."DEPARTEMENT"
(	"NOMDEPARTEMENT" VARCHAR2(100),
     PRIMARY KEY ("NOMDEPARTEMENT")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
             PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
             BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965724" ON "FIEVETL"."DEPARTEMENT" ("NOMDEPARTEMENT")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."DOMICILE"
(	"ADRESSEDOMICILE" VARCHAR2(100),
     "TYPEDEDOMICILE" VARCHAR2(100) NOT NULL ENABLE,
     "CODEPOSTALE" NUMBER(*,0) NOT NULL ENABLE,
     "NOMVILLE" VARCHAR2(100) NOT NULL ENABLE,
     PRIMARY KEY ("ADRESSEDOMICILE")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION DEFERRED
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965755" ON "FIEVETL"."DOMICILE" ("ADRESSEDOMICILE")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."ENSEIGNEMENT"
(	"IDCOURS" VARCHAR2(100),
     "IDUTILISATEUR" VARCHAR2(100),
     PRIMARY KEY ("IDCOURS", "IDUTILISATEUR")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION DEFERRED
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965803" ON "FIEVETL"."ENSEIGNEMENT" ("IDCOURS", "IDUTILISATEUR")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."ETRE_ABSENT"
(	"IDETUDIANT" VARCHAR2(100),
     "DATES" VARCHAR2(100),
     "IDCOURS" VARCHAR2(100),
     "MATIN" VARCHAR2(100),
     "JUSTIFIEE" VARCHAR2(100),
     "MOTIFABSENCE" VARCHAR2(100),
     "ESTABSENT" VARCHAR2(100),
     PRIMARY KEY ("IDETUDIANT", "DATES", "IDCOURS")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION DEFERRED
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965793" ON "FIEVETL"."ETRE_ABSENT" ("IDETUDIANT", "DATES", "IDCOURS")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."ETRE_INTERVENANT"
(	"IDMODULE" VARCHAR2(100),
     "IDUTILISATEUR" VARCHAR2(100),
     PRIMARY KEY ("IDMODULE", "IDUTILISATEUR")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION DEFERRED
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965809" ON "FIEVETL"."ETRE_INTERVENANT" ("IDMODULE", "IDUTILISATEUR")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."ETUDIANTCOURS"
(	"IDETUDIANT" VARCHAR2(100),
     "IDCOURS" VARCHAR2(100),
     PRIMARY KEY ("IDETUDIANT", "IDCOURS")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION DEFERRED
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965797" ON "FIEVETL"."ETUDIANTCOURS" ("IDETUDIANT", "IDCOURS")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."ETUDIANTS"
(	"IDETUDIANT" VARCHAR2(100),
     "PRENOMETUDIANT" VARCHAR2(100),
     "NOMETUDIANT" VARCHAR2(100),
     "CIVILITÉ" VARCHAR2(100),
     "BOURSIER" VARCHAR2(100),
     "IDADMISSION" VARCHAR2(100),
     "EMAILETUDIANT" VARCHAR2(100),
     "MAILPERSO" VARCHAR2(100),
     "NUMEROFIX" VARCHAR2(100),
     "NUMEROPORTABLE" VARCHAR2(100),
     "APPELATIONBAC" VARCHAR2(100),
     "NOMSPECIALITE" VARCHAR2(100),
     "ANNEE" NUMBER(*,0),
     "IDGROUPE" VARCHAR2(100),
     "CODETYPEFORMATION" VARCHAR2(100),
     "NOMPROMOTION" VARCHAR2(100),
     "ETATINSCRIPTION" VARCHAR2(100),
     "ANNEE_1" NUMBER(*,0),
     "CODELYCEE" VARCHAR2(100),
     "ADRESSEDOMICILE" VARCHAR2(100) NOT NULL ENABLE,
     "NOMNATIONALITE" VARCHAR2(100) NOT NULL ENABLE,
     "NOMVILLE" VARCHAR2(100) NOT NULL ENABLE,
     "DATES" VARCHAR2(100),
     PRIMARY KEY ("IDETUDIANT")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION DEFERRED
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965776" ON "FIEVETL"."ETUDIANTS" ("IDETUDIANT")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."ETUDIANTS_DATA"
(	"IDETUDIANT" NUMBER(*,0),
     "NOM" VARCHAR2(100),
     "PRENOM" VARCHAR2(100),
     "CIVILITE" VARCHAR2(100),
     "DATE_NAISSANCE" VARCHAR2(100),
     "LIEU_NAISSANCE" VARCHAR2(100),
     "DEPT_NAISSANCE" VARCHAR2(100),
     "NATIONALITE" VARCHAR2(100),
     "EMAIL" VARCHAR2(100),
     "EMAILPERSO" VARCHAR2(100),
     "DOMICILE" VARCHAR2(100),
     "CODEPOSTALDOMICILE" NUMBER(*,0),
     "VILLEDOMICILE" VARCHAR2(100),
     "PAYSDOMICILE" VARCHAR2(100),
     "TELEPHONE" VARCHAR2(100),
     "TELEPHONEMOBILE" VARCHAR2(100),
     "TYPEADRESSE" VARCHAR2(100),
     "BOURSIER" VARCHAR2(100),
     "IDADMISSION" NUMBER(*,0),
     "ANNEEADMISSION" NUMBER(*,0),
     "BAC" VARCHAR2(100),
     "SPECIALITE" VARCHAR2(100),
     "ANNEE_BAC" NUMBER(*,0),
     "MATH" FLOAT(63),
     "PHYSIQUE" FLOAT(63),
     "ANGLAIS" FLOAT(63),
     "FRANCAIS" FLOAT(63),
     "CODELYCEE" VARCHAR2(100),
     "NOMLYCEE" VARCHAR2(100),
     "VILLELYCEE" VARCHAR2(100),
     "CODEPOSTALLYCEE" NUMBER(*,0)
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."ETUDIANT_COUR_DATA"
(	"IDETUDIANT" NUMBER(*,0),
     "NOM" VARCHAR2(100),
     "PRENOM" VARCHAR2(100),
     "IDCOURS" NUMBER(*,0),
     "IDMODULE" NUMBER(*,0),
     "NOMMODULE" VARCHAR2(100),
     "IDSEMESTRE" NUMBER(*,0),
     "NUMEROSEMESTRE" NUMBER(*,0),
     "PROMOTION" VARCHAR2(100)
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."ETUDIANT_SEMESTRE_DATA"
(	"IDETUDIANT" NUMBER(*,0),
     "NOM" VARCHAR2(100),
     "PRENOM" VARCHAR2(100),
     "ETATINSCRIPTION" VARCHAR2(100),
     "IDSEMESTRE" NUMBER(*,0),
     "NUMEROSEMESTRE" NUMBER(*,0),
     "PROMOTION" VARCHAR2(100),
     "DATEDEBUTSEMESTRE" VARCHAR2(100),
     "DATEFINSEMESTRE" VARCHAR2(100),
     "CODETYPEFORMATION" VARCHAR2(100),
     "NOMTYPEFORMATION" VARCHAR2(100)
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."EVALUATIONS"
(	"IDEVALUATION" VARCHAR2(100),
     "COEFFICIENT" VARCHAR2(100),
     "IDUTILISATEUR" VARCHAR2(100) NOT NULL ENABLE,
     PRIMARY KEY ("IDEVALUATION")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION DEFERRED
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965771" ON "FIEVETL"."EVALUATIONS" ("IDEVALUATION")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."GROUPES"
(	"IDGROUPE" VARCHAR2(100),
     "NOMGROUPE" VARCHAR2(100),
     PRIMARY KEY ("IDGROUPE")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
             PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
             BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965729" ON "FIEVETL"."GROUPES" ("IDGROUPE")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."GROUPES_DATA"
(	"IDETUDIANT" NUMBER(*,0),
     "NOM" VARCHAR2(100),
     "PRENOM" VARCHAR2(100),
     "IDGROUPE" NUMBER(*,0),
     "NOMGROUPE" VARCHAR2(100),
     "IDSEMESTRE" NUMBER(*,0),
     "NUMEROSEMESTRE" NUMBER(*,0),
     "PROMOTION" VARCHAR2(100)
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."INSCRIPTION"
(	"ETATINSCRIPTION" VARCHAR2(100),
     PRIMARY KEY ("ETATINSCRIPTION")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
             PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
             BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965728" ON "FIEVETL"."INSCRIPTION" ("ETATINSCRIPTION")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."LYCEES"
(	"CODELYCEE" VARCHAR2(100),
     "NOMLYCEE" VARCHAR2(100),
     "CODEPOSTALE" NUMBER(*,0),
     "NOMVILLE" VARCHAR2(100),
     PRIMARY KEY ("CODELYCEE")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION DEFERRED
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965759" ON "FIEVETL"."LYCEES" ("CODELYCEE")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."MATIERE"
(	"MATIERE" VARCHAR2(100),
     PRIMARY KEY ("MATIERE")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION DEFERRED
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965745" ON "FIEVETL"."MATIERE" ("MATIERE")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."MODULES"
(	"IDMODULE" VARCHAR2(100),
     "HEURECM" VARCHAR2(100),
     "HEURETD" VARCHAR2(100),
     "HEURETP" VARCHAR2(100),
     "COEFFICIENT" VARCHAR2(100),
     "NOMMODULE" VARCHAR2(100),
     "CODEMODULE" VARCHAR2(100),
     "IDUE" VARCHAR2(100),
     "IDUTILISATEUR" VARCHAR2(100),
     PRIMARY KEY ("IDMODULE")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION DEFERRED
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965762" ON "FIEVETL"."MODULES" ("IDMODULE")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."NATIONALITE"
(	"NOMNATIONALITE" VARCHAR2(100),
     PRIMARY KEY ("NOMNATIONALITE")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
             PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
             BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965722" ON "FIEVETL"."NATIONALITE" ("NOMNATIONALITE")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."NOTE"
(	"NOTE" NUMBER(15,10),
     PRIMARY KEY ("NOTE")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION DEFERRED
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965744" ON "FIEVETL"."NOTE" ("NOTE")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."NOTER"
(	"IDETUDIANT" VARCHAR2(100),
     "IDEVALUATION" VARCHAR2(100),
     "NOTE" VARCHAR2(100),
     PRIMARY KEY ("IDETUDIANT", "IDEVALUATION")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION DEFERRED
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965812" ON "FIEVETL"."NOTER" ("IDETUDIANT", "IDEVALUATION")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."NOTES_DATA"
(	"IDETUDIANT" NUMBER(*,0),
     "NOM" VARCHAR2(100),
     "PRENOM" VARCHAR2(100),
     "NOTE" FLOAT(63),
     "IDEVALUATION" NUMBER(*,0),
     "COEFFICIENT" FLOAT(63),
     "NOTE_MAX" FLOAT(63),
     "IDCOURS" NUMBER(*,0),
     "IDMODULE" NUMBER(*,0),
     "NOMMODULE" VARCHAR2(100),
     "IDSEMESTRE" NUMBER(*,0),
     "PROMOTION" VARCHAR2(100),
     "NUMSEMESTRE" NUMBER(*,0),
     "IDUTILISATEUR" NUMBER(*,0),
     "NOMUTILISATEUR" VARCHAR2(100),
     "PRENOMUTILISATEUR" VARCHAR2(100)
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."PAYS"
(	"NOMPAYS" VARCHAR2(100),
     PRIMARY KEY ("NOMPAYS")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION DEFERRED
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965742" ON "FIEVETL"."PAYS" ("NOMPAYS")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."POSTALE"
(	"CODEPOSTALE" NUMBER(*,0),
     PRIMARY KEY ("CODEPOSTALE")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
             PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
             BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965739" ON "FIEVETL"."POSTALE" ("CODEPOSTALE")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."PROMOTION"
(	"NOMPROMOTION" VARCHAR2(100),
     PRIMARY KEY ("NOMPROMOTION")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
             PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
             BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965735" ON "FIEVETL"."PROMOTION" ("NOMPROMOTION")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."ROLES"
(	"NOMROLE" VARCHAR2(100),
     PRIMARY KEY ("NOMROLE")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
             PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
             BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965741" ON "FIEVETL"."ROLES" ("NOMROLE")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."SEMESTRE"
(	"IDSEMESTRE" VARCHAR2(100),
     "NUMEROSEMESTRE" VARCHAR2(100),
     "DEBUT" VARCHAR2(100) NOT NULL ENABLE,
     "FIN" VARCHAR2(100) NOT NULL ENABLE,
     PRIMARY KEY ("IDSEMESTRE")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
             PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
             BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965732" ON "FIEVETL"."SEMESTRE" ("IDSEMESTRE")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."SPECIALITES"
(	"NOMSPECIALITE" VARCHAR2(100),
     PRIMARY KEY ("NOMSPECIALITE")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION DEFERRED
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965723" ON "FIEVETL"."SPECIALITES" ("NOMSPECIALITE")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."TYPEDOMICILE"
(	"TYPEDEDOMICILE" VARCHAR2(100),
     PRIMARY KEY ("TYPEDEDOMICILE")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION DEFERRED
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965738" ON "FIEVETL"."TYPEDOMICILE" ("TYPEDEDOMICILE")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."TYPEENSEIGNANT"
(	"TYPEENSEIGNANT" VARCHAR2(100),
     PRIMARY KEY ("TYPEENSEIGNANT")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
             PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
             BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965740" ON "FIEVETL"."TYPEENSEIGNANT" ("TYPEENSEIGNANT")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."TYPEFORMATION"
(	"CODETYPEFORMATION" VARCHAR2(100),
     "NOMTYPEFORMATION" VARCHAR2(100),
     PRIMARY KEY ("CODETYPEFORMATION")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
             PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
             BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965727" ON "FIEVETL"."TYPEFORMATION" ("CODETYPEFORMATION")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."UE"
(	"IDUE" VARCHAR2(100),
     "CODEUE" VARCHAR2(100),
     "NOMUE" VARCHAR2(100),
     "COEFFICIENTUE" VARCHAR2(100),
     "NOMBREECTS" VARCHAR2(100),
     PRIMARY KEY ("IDUE")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
             PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
             BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965736" ON "FIEVETL"."UE" ("IDUE")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."UTILISATEURS"
(	"IDUTILISATEUR" VARCHAR2(100),
     "PRENOMUTILISATEUR" VARCHAR2(100),
     "NOMUTILISATEUR" VARCHAR2(100),
     "MAILUTILISATEUR" VARCHAR2(100),
     "TYPEENSEIGNANT" VARCHAR2(100),
     "NUMBUREAU" VARCHAR2(100),
     PRIMARY KEY ("IDUTILISATEUR")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION DEFERRED
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965749" ON "FIEVETL"."UTILISATEURS" ("IDUTILISATEUR")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."UTILISATEURSROLES"
(	"IDUTILISATEUR" VARCHAR2(100),
     "NOMROLE" VARCHAR2(100),
     PRIMARY KEY ("IDUTILISATEUR", "NOMROLE")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION DEFERRED
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965790" ON "FIEVETL"."UTILISATEURSROLES" ("IDUTILISATEUR", "NOMROLE")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."UTILISATEURS_DATA"
(	"IDUTILISATEUR" NUMBER(*,0),
     "NOM" VARCHAR2(100),
     "PRENOM" VARCHAR2(100),
     "EMAIL" VARCHAR2(100),
     "TYPEENSEIGNANT" VARCHAR2(100),
     "NUMBUREAU" VARCHAR2(100),
     "TELEPHONEBUREAU" NUMBER(*,0),
     "ROLE" VARCHAR2(100)
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "ANNEE1" ;
;

CREATE TABLE "FIEVETL"."VILLES"
(	"NOMVILLE" VARCHAR2(100),
     "NOMPAYS" VARCHAR2(100),
     "NOMDEPARTEMENT" VARCHAR2(100),
     PRIMARY KEY ("NOMVILLE")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
             TABLESPACE "ANNEE1"  ENABLE
) SEGMENT CREATION DEFERRED
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    TABLESPACE "ANNEE1" ;

CREATE UNIQUE INDEX "FIEVETL"."SYS_C00965746" ON "FIEVETL"."VILLES" ("NOMVILLE")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    TABLESPACE "ANNEE1" ;
;

